### PR TITLE
Update flow and prettier to latest versions

### PR DESCRIPTION
**Pull request by harrysarson**
Later versions of flow require the return type of some functions to be specified.

Only the most recent versions of prettier can process the extra type comments that are required. I also had to add the `--parser flow` command line argument to prettier to stop it messing around with the comment.

This pull request is the result of updating the two packages and making the minimal changes required for ci to pass.

### CODE REVIEW

**Comment by harrysarson** [comment]
CI failure is unrelated - although it would be good to re run CI once #348 lands just to make sure.

**Comment by harrysarson** [comment]
What is the status on these pull requests? They don't contain any urgent changes but they have been open for over two months now.

As always, if there is anything helpful I can do, I would be very happy to do so!

**Comment by mgold** [comment]
@rtfeldman It might be time to give Harry a commit bit and permission to use it.

**Comment by harrysarson** [comment]
Cheeky ping?

**Comment by avh4** [comment]
Looks great!  I included this in https://github.com/rtfeldman/node-test-runner/pull/372

**Comment by harrysarson** [comment]
Thanks!

**Pull request merged**
