### PR TITLE
Fix "no tests found" errors for json and junit

### PR DESCRIPTION
**Pull request by lydell**
Fixes https://github.com/rtfeldman/node-test-runner/issues/495

I consider this something that _should_ be a compile time error. It isn’t currently because we run the JS to figure out which exposed values are of type Test. But it used to be in 0.19.1-revision4 and older.

All compile time errors are printed human readable to stderr. This PR makes sure that happens for this error as well. There was already code in place for this, but it was only for the `console` reporter. I changed it to apply to all reporters.

I have not been able to figure out how to do a regression test for this.

### CODE REVIEW

**Comment by harrysarson** [comment]
@lydell please review 2b50eca :) Otherwise we are good to merge.

**Comment by lydell** [comment]
I think the tests look good! 👍 

Maybe we should disable this lint rule? https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-setup-in-describe.md

I don’t understand why it’s complaining

**Review by lydell — COMMENTED** [review]
Great tests!

**Comment by harrysarson** [comment]
After an embarrassing number of attempts we finally got there

**Pull request merged**
