### PR TITLE
Bugfix incorrect attribute name

### PR DESCRIPTION
**Pull request by jhf**
As per the spec, or the closest thing there is to one,
ref "https://help.catchsoftware.com/display/ET/JUnit+Format".

### CODE REVIEW

**Comment by harrysarson** [comment]
Test failure is due to flakiness in CI do not worry about that.

This looks good to me. Just to continue the [conversation about validation](https://github.com/rtfeldman/node-test-runner/issues/354#issuecomment-702226054), what I am thinking is this:

1. Without this PR, when you run an elm-test test suite in jenkins, jenkins complains about the JUnit xml format.
2. With this PR Jenkins is (presumably) happy to run elm-test test suites!

Therefore, Jenkins must run some sort of program that parses the JUnit XML which can complain about the formatting. If this program was available and we could set it up in our CI (maybe just linux to keep it easy) running with some test output, we would have confidence that the XML elm-test produces is valid!

Saying that, if this all sounds like too much work I am happy to merge this as is.

**Comment by harrysarson** [comment]
Re-opening to see if we can get CI green!

**Comment by harrysarson** [comment]
@jhf do you have any more thoughts here?

**Comment by jhf** [comment]
> Test failure is due to flakiness in CI do not worry about that.

Ok

> This looks good to me. Just to continue the [conversation about validation](https://github.com/rtfeldman/node-test-runner/issues/354#issuecomment-702226054), what I am thinking is this:
> 
> 1. Without this PR, when you run an elm-test test suite in jenkins, jenkins complains about the JUnit xml format.
> 2. With this PR Jenkins is (presumably) happy to run elm-test test suites!

Yes

> Therefore, Jenkins must run some sort of program that parses the JUnit XML which can complain about the formatting.

No, it tries to parse the xml, and fails if some required field is missing, do notice that Jenkins is not strict on all fields/attributes,
just those it cares about/expect, and it does not require a validated xml.

> If this program was available and we could set it up in our CI (maybe just linux to keep it easy) running with some test output, we would have confidence that the XML elm-test produces is valid!

Maybe, because the different tags and attributes depend on the outcomes, no failing tests, some failing tests, and on jenkins, we would need to produce a variety of test cases, and run the jenkins parser from the command line.
That should be possible, but it may require some Java programming to actually run the code independent of a complete Jenkins installation.

Furthermore, I would not have complete confidence in the output, even if Jenkins work, since Jenkins doesn't validate.

I think the best bet would be to take the XSD file I mentioned in [1] and find a standalone program that can validate the xml output, using the XSD file. An XSD file contains definitions for the validity of an xml.

Glancing over the XSD, I think it requires much more than Jenkins, in particular a timestamp of the time when running the test.

> Saying that, if this all sounds like too much work I am happy to merge this as is.

I think perfect is the enemy of good - in this case, having an xml that is at least not known to be wrong is better than now. Having a fully validated xml is better, from a purity standpoint, but will make difference in Jenkins parsing the file.

[1] https://github.com/rtfeldman/node-test-runner/issues/354#issuecomment-702226054

**Comment by harrysarson** [comment]
Okay! You make good points and you make them well. Thanks for the patch!

**Pull request merged**
