### PR TITLE
Prevent many small highlighted blocks in diff.

### PR DESCRIPTION
**Pull request by harrysarson**
By comparing the number of edges of highlighted blocks to the number
of non-highlighted characters (highlighting is the result of
diffing),  messy diffs with lots of small highlighted blocks are
disabled.

Diffs will only be displayed if there are more plain characters than there
are edges highlighted blocks in both the actual and expected strings.

Fixes https://github.com/rtfeldman/node-test-runner/issues/263.

### CODE REVIEW

**Comment by harrysarson** [comment]
I have not added a test as there seemed to be no where to put it 😢. Here is a test I used to verify this change locally:

```elm
module Example exposing (suite)

import Expect
import Test exposing (..)


suite : Test
suite =
    describe "union type diff"
        [ test "1" <|
            \() ->
                Err { description = "An error", context = "Explanation of what went so wrong" }
                    |> Expect.equal (Ok "Success.")
        , test "2" <|
            \() ->

                Err { context = "Success" }

                    |> Expect.equal (Ok "Success.")

        , test "3" <|
            \() ->
                Err { context = "OhK3 S-u5c6c4e2s2s  4" }
                    |> Expect.equal (Ok "Success.")
        ]
```

Before:

image

After:

image

**Comment by jackfranklin** [comment]
@harrysarson this is awesome and a great change. I think we should figure out some place to put that test you were using as your test case, as I think it'll probably be a useful reference. I'm also not quite sure where in the repo it could go though.

**Comment by harrysarson** [comment]
I don't think the test runner has any tests of its elm code at all.

**Comment by harrysarson** [comment]
I have found a place to put elm unit tests but I will make a new PR for that as my idea will require some other changes. I would say to merge this as is an I will add the tests soon. :)

**Comment by jackfranklin** [comment]
It looks great to me, however I'm not familiar with this part of the codebase, so I think I'd like to let @rtfeldman have a look before merging :)

**Comment by rtfeldman** [comment]
I dig it! This has been bothering me since I added it. 😄 

Thanks @harrysarson!

**Pull request merged**
