### PR TITLE
Fix windows EADDRINUSE

### PR DESCRIPTION
**Pull request by rtfeldman**
Attempt to fix https://github.com/rtfeldman/node-test-runner/issues/275#issuecomment-418756561

### CODE REVIEW

**Comment by rtfeldman** [comment]
Huh! So everything worked without https://github.com/rtfeldman/node-test-runner/commit/963f0de986d1eaa57afd6576d8590b70deb8c76c in the mix? As in, the original bug appears to be gone?

**Comment by Y0hy0h** [comment]
I haven't yet tried getting rid of 963f0de986d1eaa57afd6576d8590b70deb8c76c, so no, for now it simply freezes before the issue in #275 can manifest.

**Comment by rtfeldman** [comment]
Ah ok - I just reverted it on the branch, so let's see how it does without it!

**Comment by Y0hy0h** [comment]
Thanks for reverting it for me. I'm a bit tired, so I wouldn't have done it myself today, but this makes it trivial to test.

And it appears that it works! I'll poke it a bit more, but it has run well a few times now.

**Comment by rtfeldman** [comment]
Appveyor now reports all passing tests and then hangs, leading to a failure.

I'm gonna diagnose that separately; seems ok now!

**Comment by Y0hy0h** [comment]
@rtfeldman It _does_ terminate without `--watch`. It still ignores <kbd>Ctrl</kbd>+<kbd>C</kbd> with `--watch`.

However, that is workable already. So thanks a lot for making this work! :)

**Comment by rtfeldman** [comment]
Thanks for your patience!

For future reference, would you mind opening a different issue for the `Ctrl-C` issue?

It won't be a release blocker, but I'd like to keep track of it!

**Pull request merged**
